### ISSUE TITLE
SAM4S4C Flash Busy Timeout

### ISSUE THREAD

**Issue by jamesfowkes** [abcminiuser/sam-ba-loader#13]
Hi,

I have a custom SAM4S4C board that I'd like to get working with your application (I find the Microchip tools to be flaky at best).

Extra possibly relevant information: I can flash the chip using the Microchip SAM-BA 2.18 tool, at least under certain conditions. It seems to be very dependent on the exact state of the device, whether it has been erased or not, whether any flash operations have already been performed.

When I use sam-ba-loader, it can read the chip ID but when it tries to read the NVM bits, it times out waiting for the FRDY bit to be set:

```
PS C:\Users\James Fowkes\Documents\sam-ba-loader> py.exe .\SAMBALoader.py -v -p COM12 info
INFO:root:START 2023-04-04T13:33:07.190858
INFO:SAMBALoader.Transports.Serial:Open COM12 @ 115200 8N1
INFO:root:SAMBA Version: v1.13 RC2 Feb 20 2013 13:25:17
Chip identifiers
CPUID @ 0xE000ED00: 0x410FC241
        Implementer:    ARM
        Architecture:   ARMv7-M
        Version:        r0p1
        Part:           Cortex-M3/Cortex-M4
CHIPID @ 0x400E0740: 0x28AB09E1
        Version:        1
        Processor:      Cortex-M4
        Architecture:   SAM4SxC (100-pin version)
        Flash Bank 0:   256KB
        Flash Bank 1:   NONE
        SRAM:           64KB
        Extended ID:    0
Discovered Part: ATSAM4S4C
WARNING:root:Selected part is currently untested
Traceback (most recent call last):
  File "C:\Users\James Fowkes\Documents\sam-ba-loader\SAMBALoader.py", line 283, in <module>
    print(part.get_info())
  File "C:\Users\James Fowkes\Documents\sam-ba-loader\SAMBALoader\Parts\CortexM3_4.py", line 57, in get_info
    ret += self.flash_controllers[0].get_info()
  File "C:\Users\James Fowkes\Documents\\sam-ba-loader\SAMBALoader\FlashControllers\EEFCFlash.py", line 214, in get_info
    ret += '\tGPNVM bits: ' + str(self.read_gpnvm()) + '\n'
  File "C:\Users\James Fowkes\Documents\sam-ba-loader\SAMBALoader\FlashControllers\EEFCFlash.py", line 161, in read_gpnvm
    self._command('GGPB')
  File "C:\Users\James Fowkes\Documents\sam-ba-loader\SAMBALoader\FlashControllers\EEFCFlash.py", line 118, in _command
    self._wait_while_busy()
  File "C:\Users\James Fowkes\Documents\sam-ba-loader\SAMBALoader\FlashControllers\EEFCFlash.py", line 100, in _wait_while_busy
    raise Exception('Flash busy: timeout. FSR: ' + str(self.samba.read_word(self.regs_base_address + self.FSR_OFFSET)))
Exception: Flash busy: timeout. FSR: 0
```

I have looked through the repo and all the definitions, offsets etc. for this part _look_ OK.

Any advice you can offer would be appreciated.

**Comment by ezonca-thorlabs** [comment]
Having the same issue on the SAM4S2. Did you end up finding any solution? I also double-checked addresses, registers, and offsets and everything seems correct.
